### ISSUE TITLE
Run tests against a given upstream branch when one is provided

### ISSUE THREAD

**Issue by danielbachhuber** [danielbachhuber/pantheon-wordpress-upstream#1]
It should be possible to trigger a build that uses a given upstream branch.

**Comment by danielbachhuber** [comment]
@stevector I [got this working](https://circleci.com/gh/danielbachhuber/pantheon-wordpress/9) on a [fork of the Pantheon WordPress upstream](https://github.com/danielbachhuber/pantheon-wordpress), and gave Greg a walk though on Google Hangout.

When you have a moment, it would be great to have you follow these setup steps on the Pantheon WordPress upstream itself. Then, we can discuss what remaining abstractions we should implement to call this issue closed.

Happy to hear any feedback, opinions, etc. you might have.

### Setup Steps

#### 1. Have CircleCI follow https://github.com/pantheon-systems/wordpress to start builds

#### 2. Enable Ubuntu 14.04 in the Build Environment

![image](https://cloud.githubusercontent.com/assets/36432/17006065/09daf692-4e93-11e6-9bd9-103f41d7c9ee.png)

#### 3. Add `TERMINUS_ENV`, `TERMINUS_SITE` and `TERMINUS_TOKEN` environment variables

![image](https://cloud.githubusercontent.com/assets/36432/17006090/28156a3e-4e93-11e6-8bb8-6f0b59de7433.png)

```
TERMINUS_ENV=ci-$CIRCLE_BUILD_NUM
TERMINUS_SITE=wordpress-upstream
TERMINUS_TOKEN=<secret>
```

### 4. Add a SSH key with push access to the Pantheon site

![image](https://cloud.githubusercontent.com/assets/36432/17006110/5e49cece-4e93-11e6-8b98-aae724aa76f0.png)

### 5. Configure dependency commands

![image](https://cloud.githubusercontent.com/assets/36432/17006124/76d2c7c0-4e93-11e6-87b5-2531cd10c880.png)

```
echo "date.timezone = 'US/Central'"  > /opt/circleci/php/5.6.22/etc/conf.d/xdebug.ini
```

```
curl https://github.com/pantheon-systems/terminus/releases/download/0.11.2/terminus.phar -L -o /home/ubuntu/bin/terminus && chmod +x /home/ubuntu/bin/terminus
terminus auth login --machine-token=$TERMINUS_TOKEN
git clone git@github.com:pantheon-systems/pantheon-wordpress-upstream.git test-suite
cd test-suite; composer install; cd ..
```

Couple of things to note here:
- I'm not quite sure that CircleCI is running PHP 5.6.22, because there doesn't appear to be a way to set the PHP version from the backend. We may be stuck with whatever the default for the environment is.
- I'm installing Terminus via Phar file because Circle oddly [installs to `$HOME/.config/composer`](https://pantheon.slack.com/archives/wordpress/p1469049871000096) when you use `composer global require` from a definition set in the backend.

### 6. Configure test commands

![image](https://cloud.githubusercontent.com/assets/36432/17006272/6a147550-4e94-11e6-97a4-f68fdc336cd5.png)

This likely makes sense to abstract to a script tracked in the test suite, but I'm not quite sure what to call it.

```
./test-suite/prepare.sh
terminus site set-connection-mode --mode=git
git remote add pantheon $(terminus site connection-info --field=git_url)
git push -f pantheon $CIRCLE_BRANCH:$TERMINUS_ENV
terminus site set-connection-mode --mode=sftp
cd test-suite; ./test.sh; cd ..
./test-suite/cleanup.sh
```

Push a branch on the repo to trigger a build, and voila!

**Comment by stevector** [comment]
Tests are now running on the main WordPress repo: 

https://circleci.com/gh/pantheon-systems/WordPress
https://github.com/pantheon-systems/WordPress/pull/87
