### ISSUE TITLE
Consider renaming this repo

### ISSUE THREAD

**Issue by danielbachhuber** [danielbachhuber/pantheon-wordpress-upstream#21]
Should we call this `pantheon-wordpress-upstream-tests`, to explicitly denote it contains tests?

**Comment by stevector** [comment]
Yes, I think it is worth clarifying. What do you think @greg-1-anderson?

**Comment by greg-1-anderson** [comment]
Yes, I agree that the name should contain "tests".  The proposed name is fine, but perhaps `pantheon-wordpress-tests` would be adequate, and shorter.  I'm fine with either variant, though.

**Comment by danielbachhuber** [comment]
> The proposed name is fine, but perhaps `pantheon-wordpress-tests` would be adequate, and shorter. I'm fine with either variant, though.

Given we have two test suites, it's probably better to be more explicit with both.

**Comment by stevector** [comment]
Agreed. I've renamed. Follow up: https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests/pull/23
