### ISSUE TITLE
Packagist not seeing update

### ISSUE THREAD

**Issue by stevector** [danielbachhuber/pantheon-wordpress-upstream#42]
Packagist still sees https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests/commit/c257bab30afb82f8586ac20e3de030003809c196 as the commit to use when composer asks for `dev-master`.

@greg-1-anderson any idea why that is the case? https://packagist.org/packages/pantheon-systems/pantheon-wordpress-upstream-tests

@ataylorme and I noticed this problem in https://github.com/pantheon-systems/solr-power/pull/173

**Comment by greg-1-anderson** [comment]
The package is not set to auto-update. Configure auto-updates per [my BADCamp presentation](http://bit.ly/2dJown3). In the short term, try pressing the `update` button.

**Comment by stevector** [comment]
@greg-1-anderson, I don't see an `update` button. I think my packagist username (also stevector) would need access to this project.

**Comment by greg-1-anderson** [comment]
I see the update button. Did I add this project to packagist? I don't remember. 👅 

I'll set up auto-updates for you. I don't know how to give multiple users access to a Packagist project.

**Comment by greg-1-anderson** [comment]
Ah ha. There is a gray "+" in the upper-right corner of each packagist project. Clicking on this reveals an "add maintainer" field with a big green confirmation button. Took me a while to find that. I added you to that project.

**Comment by greg-1-anderson** [comment]
I set the project to auto-update for you.
