### ISSUE TITLE
Figure out how these tests can be used with plugins

### ISSUE THREAD

**Issue by danielbachhuber** [danielbachhuber/pantheon-wordpress-upstream#6]
Because these tests establish expectations for how WordPress should behave on Pantheon, it would be useful to run them on the Pantheon plugins:
- [x] https://github.com/pantheon-systems/wp-redis/
- [x] https://github.com/pantheon-systems/wp-saml-auth/
- [x] https://github.com/pantheon-systems/wp-native-php-sessions/
- [x] https://github.com/pantheon-systems/solr-power

**Comment by danielbachhuber** [comment]
@stevector WP SAML Auth presents a bit of a challenge because it has a custom login flow, which means all of the setup steps will need to be slightly different. Ideas for an easy way around this?

**Comment by stevector** [comment]
I think we should write a custom step like "Given I am logged in as an administrator" and swap out the step definition. I can work on that next week.

**Comment by stevector** [comment]
PR for upstream test in SAML plugin: https://github.com/pantheon-systems/wp-saml-auth/pull/36

**Comment by danielbachhuber** [comment]
🚢 🚢 🚢 

Nice work on this!
